### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by Monaco-a-Knox** [Akaruzi/dies_aitrans#4]
Hello.

If I understand correctly, your patch works by inserting the script inside the .exe using Resource Hacker, correct? Is it possible to insert images and voice files inside it too? 

I tried to download your patch, but Windows Defender says it contains a virus and deletes it automatically.

**Comment by Akaruzi** [comment]
Good morning!

I'm not entirely sure if the patch can be used for images and voice files. I've been told by another developer that old games based on malie have a script file (exec.dat) nested in the exe, while new games are nested into data.dat. However, malie seems to retain the setting, as it will read the script in the exe first. Inserting images and voice files might not be possible under the same circumstances.

I've tested the patch and it worked correctly. I'm not sure why it triggered a virus alert. In any case, you can try packing it yourself.

I truly appreciate your work on the translation. Without the tool you've built, I wouldn't have been able to make any progress. Thank you!

I hope this helps! Let me know if you need further assistance

________________________________
发件人: Monaco-a-Knox ***@***.***>
发送时间: 2024年1月17日 0:05
收件人: Akaruzi/dies_aitrans ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Akaruzi/dies_aitrans] Patch (Issue #4)


Good morning.

If I understand correctly, your patch works by inserting the script inside the .exe using Resource Hacker, correct? Is it possible to insert images and voice files inside it too?

I tried to download your patch, but Windows Defender says it contains a virus and deletes it automatically.

―

**Comment by Monaco-a-Knox** [comment]
Maybe it's a false positive because the .exe has been modified? 7zip doesn't even let me unzip it.

It's a good idea to insert the script inside the executable, but it's useless for me because it's necessary to modify videos, images and audio to apply the full patch.

**Comment by Cosetto** [comment]
@Akaruzi [Malie's packer](https://github.com/satan53x/SExtractor/tree/main/tools/Malie)
You just need to fill the bytes from offset 0x10~0x17 of original archive, it will auto match the database
![image](https://github.com/Akaruzi/dies_aitrans/assets/81801486/56fb2783-d9c4-4b7e-a747-177591a9417e)
Or type the game name from database_malie.json
![image](https://github.com/Akaruzi/dies_aitrans/assets/81801486/a9e84ad2-2067-413a-b4bd-8568321a5181)
Create data5.dat, data6.dat, data7.dat, etc with right path structure will work like a patch.

**Comment by Monaco-a-Knox** [comment]
After a few failures, it finally worked.
For the DX version, the hex is 50 1D 09 DE BE 3C 5C 9E

Unfortunately it's not perfect because I want to replace some images, but they're in .png, which makes the game ignore them...

The game also ignores the "arrow.cur" file.

**Comment by Akaruzi** [comment]
@Monaco-a-Knox 
I just found solution. To replace images, you can modify the string in the exec.str.txt to a name that does not exist in the package. Malie can read from the data folder if the file does not exist in the package.
![图片](https://github.com/Akaruzi/dies_aitrans/assets/119655555/c4742bd3-9d2a-4338-981a-9089062aa6da)
![图片](https://github.com/Akaruzi/dies_aitrans/assets/119655555/ad12ad85-213d-4d47-a171-2a6a15c1d485)
And cursor file might also work.

**Comment by Akaruzi** [comment]
@Cosetto 
It works. Thank you!

**Comment by Monaco-a-Knox** [comment]
@Akaruzi 

It doesn't seem to be working... When I modify the string to a name that does not exist in the package, game don't display nothing. If I change "23_a" to "teia", it no longer works.

Also,  images like "03_0" doesn't exist inside exec.str.txt, nor does image "03_2", only "03_1".

Cursor can be restored simply by creating a "data/system/arrow.cur" folder.

Edit: "it worked now", but instead of displaying my .png, the game displays an "error" message in the corner of the screen.

I'll continue using GARbro and extracting all the content.

**Comment by Akaruzi** [comment]
I tried modifying '23_a' to 'teia', and it works with .png files. To avoid errors, it's necessary to adjust the resolution to match the extracted file, such as 1600x906. However, the displayed picture is magnified and does not look good.
![图片](https://github.com/Akaruzi/dies_aitrans/assets/119655555/531f5687-67fa-492a-b73a-61a82b94f5f3)
![图片](https://github.com/Akaruzi/dies_aitrans/assets/119655555/5a670abb-1c70-4c2b-974c-c3cef7387dce)
![图片](https://github.com/Akaruzi/dies_aitrans/assets/119655555/f95661bd-2697-4599-a4b1-8f04886329e9)
Malie prioritizes reading the .dat file with the larger number. I pack a new dat file with uncensored version "tex" folder and it does work. That might be the solution.
![图片](https://github.com/Akaruzi/dies_aitrans/assets/119655555/2ef523a7-58e0-4b5b-80f3-481d804029b7)

**Comment by Monaco-a-Knox** [comment]
It was a mistake on my part.

Images were in fact being replaced in-game (with the wrong resolution). However, I was checking them inside the Gallery, which is still displaying the original .dzi.

In other words: I'm an dumb and I spent a whole day trying to fix something that wasn't broken.

Changing the names that appear between chapters would be a lot of work, so I'm giving up on that part. Ideally, I'd like to extract the equivalent .dzi files from the Nintendo Switch version, but I don't know how to extract the .dat files from it.

**Comment by Cosetto** [comment]
> Nintendo Switch version

Well, we need to debug it somehow to find the keys for extracting. But does Switch version have exe for debugging?

**Comment by Monaco-a-Knox** [comment]
> > Nintendo Switch version
> 
> Well, we need to debug it somehow to find the keys for extracting. But does Switch version have exe for debugging?

https://github.com/masagrator/DiesIraeScenario

![unknown.png](https://github.com/Akaruzi/dies_aitrans/assets/58667780/ffd9df86-cfd6-4b3a-9b80-e4e858cb0f5f)

**Comment by Cosetto** [comment]
If you don't know, [GARbro mod](https://github.com/crskycode/GARbro/releases) had added support for Dies irae \~Interview with Kaziklu Bey\~ (steam).

**Comment by Akaruzi** [comment]
@Monaco-a-Knox  @Cosetto
Hi  Knox adn Cosetto,

I've completed the Chinese translation work for Dies Irae. Allow me to share some points with you, in case you might not know. The Steam version of Dies Irae actually works with the patch.dat file in the data3.dat file , which differs from exec.dat. The script extracted from patch.dat is longer than that in exec.dat.

To create a patch, you can utilize the Enigma Virtual Box. Simply pack malie.ini and data5.dat, which contain the script file, with malie.exe. This will make it convenient to execute the patch and reserve the original language patch. You can see how my patch functions by checking out the release in this repo.

Regarding the censored CG in diaa, I've extracted all uncensored CG from diaef and packed them into [data9.dat](https://github.com/Akaruzi/dies_aitrans/blob/master/data9.dat) in the repo.

Currently, I've begun working on KKK and have found a much efficient method to edit images and display the vertical message, which I've introduced in another repo [kkk_r18_patch](https://github.com/Akaruzi/kkk_r18_patch).

I hope this information proves helpful.

**Comment by Cosetto** [comment]
Oh, that's nice. I hope the choice would work out too.

**Comment by Monaco-a-Knox** [comment]
Congratulations. My patch is almost ready too (7 chapters to go). 

I'm using [Github actions](https://github.com/Monaco-a-Knox/Dia-da-Ira/blob/main/dependencies/compile_pc.py) to compile it. Script, uncensored voices and CG inside data5.dat. Only one CG remains censored because the original looks too stretched, and the censored version still shows Rusalka's pantsu.

(I also don't know how extract data1.dat content from Switch. Dir-A instuctions to find keys is alien to me)

Regarding KKK, my friend is translating it, so I don't know the progress, but I've fixed almost all engine problems, except for two things:
- automatic line break (maybe it's a .dll inside the .exe... no idea how english version of DI fixed it)
- vertical choices

**Comment by Cosetto** [comment]
> I also don't know how extract data1.dat content from Switch. Dir-A instuctions to find keys is alien to me

I know how to, I found the keys for Interview with Kaziklu Bey (steam). To that, we need the exe to debug, does switch even has exe?

**Comment by Monaco-a-Knox** [comment]
>> I know how to, I found the keys for Interview with Kaziklu Bey (steam). To that, we need the exe to debug, does switch even has exe?

Yes, I've sent an image of the game running on Windows. Just unpack .nsp content using hactool and play (although it has some sound issues.) Unfortunately, I don't have it anymore.

data3.dat and data4.dat files are open and don't need to be extracted.

**Comment by Monaco-a-Knox** [comment]
[Here](https://files.catbox.moe/4mqeri.7z) @Cosetto

**Comment by Cosetto** [comment]
Need full game
![image](https://github.com/Akaruzi/dies_aitrans/assets/81801486/c89d6df6-aad3-4bd6-9d01-2e72341d0185)

**Comment by Akaruzi** [comment]
@Cosetto 
https://www.ziperto.com/dies-irae-amantes-amentes-switch/
Mega: https://mega.nz/file/8z0VkKhJ#flPxnXK_geb9ZiNyQdn2uU235SQLlsx8sdNixx1qJ7U

**Comment by Akaruzi** [comment]
@Monaco-a-Knox 
> Only one CG remains censored because the original looks too stretched, and the censored version still shows Rusalka's pantsu.

To replace the CGs you need to use svg file of uncensored ones, cause steam version is actually different from dx version.

> automatic line break (maybe it's a .dll inside the .exe... no idea how english version of DI fixed it)

What do you mean about automatic line break? If you mean kkk break every line and doesn't have vertical messageframe, you can edit the normal.svg like me.

**Comment by Cosetto** [comment]
I checked, but looks like the encryption type doesn't match the one uses on window

**Comment by Monaco-a-Knox** [comment]
>To replace the CGs you need to use svg file of uncensored ones, cause steam version is actually different from dx version.

I know... but the original image seems stretched. Maybe because it was originally made for 4:3... In that specific scene, a small _panchira_  is more natural imo.

>What do you mean about automatic line break? 

I guess the right word here is "wordwarp".

>I checked, but looks like the encryption type doesn't match the one uses on window

Sad, but well... I can release a patch without fix names in-between chapters. Isn't a big problem.

**Comment by Akaruzi** [comment]
> I guess the right word here is "wordwarp".

I seem to understand. The KKK uses a lot of Jindai moji which display as unrecognizable unicode. I remember SacanaWrapper will skip and break directly while malie_script_tool will reserve them. The identifier `[n]` will also break lines, you can just delete them which doesn't cause error of making exec.dat.
![图片](https://github.com/Akaruzi/dies_aitrans/assets/119655555/260a7d53-8908-460f-a601-262d75038097)
![图片](https://github.com/Akaruzi/dies_aitrans/assets/119655555/39ba7b28-ea1a-498d-ac8f-341169723f29)

**Comment by Monaco-a-Knox** [comment]
No, I mean...
![image-3.png](https://github.com/Akaruzi/dies_aitrans/assets/58667780/caad8d05-0ba1-4745-9419-e875ffe2e71d)



I need to add millions [n] to fix it. This problem is less frequent using horizontal textbox, but still a problem.

**Comment by Cosetto** [comment]
I have a code to wrap the script format:
◇B000004C◇「ふぅ、やっと昼休みか……」
◆B000004C◆「ふぅ、やっと昼休みか……」

But you need to improve it for KKK's script.
```
import os, re, textwrap

def walk(adr):
    mylist = []
    for root, dirs, files in os.walk(adr):
        for name in files:
            adrlist = os.path.join(root, name)
            mylist.append(adrlist)
    return mylist


def create_file(dstname):
    if not os.path.exists(os.path.dirname(dstname)):
        os.makedirs(os.path.dirname(dstname))

fl = walk('script')
sumlen = 0

for fn in fl:
    src = open(fn, 'r', encoding='u16')
    script_lines = src.readlines()

    dstname = 'script_done' + fn[6:-3] + 'txt'
    create_file(dstname)
    dst = open(dstname, 'w', encoding='u16')
    
    #get the number of lines
    line_count = 0
    for line in script_lines: line_count += 1
    
    for i in range(line_count):
      line = script_lines[i]

      #split up lines that are too long to fit on-screen
      line_len = len(line)
      new_line = ""
      done_newline = False
      if not ord(line[0]) == 9670: continue #first character must be ◆
      message_len = 0
      is_message = 0
      
      for j in range(line_len):
        character = line[j]
        if ord(character) == 9670: #find the second ◆, where message starts
          is_message += 1

        if is_message >= 2:
          if character == " " and message_len > 55: #add a [n] after a space, when character count is over 40
            new_line = new_line + "[n]"
            message_len = 0
            continue
            
        if is_message >= 2: message_len += 1
        new_line = new_line + character
        
      script_lines[i] = new_line
 
    dst.writelines(script_lines)
    dst.close()
```
Dependency:
pip3 install textwrap3

**Comment by Monaco-a-Knox** [comment]
Nice. Seems good. I'll teste it later.
Not the perfect solution, but it will help alot. Thank you.

Since extract Switch's content is impossible, I believe we can close this issue now.

**Comment by Cosetto** [comment]
[malie.zip](https://github.com/Akaruzi/dies_aitrans/files/15195709/malie.zip)
@Akaruzi KKK Akebono's pure exe. I just found how to remove alpharom from executable

**Comment by Akaruzi** [comment]
> [malie.zip](https://github.com/Akaruzi/dies_aitrans/files/15195709/malie.zip) @Akaruzi KKK Akebono's pure exe. I just found how to remove alpharom from executable

You are my hero, man! Now I can pack the script file and executable with enigmavb to create a separate patch. Thanks so much! ! !

**Comment by Cosetto** [comment]
Optional: I forgot to shrink the exe back to smaller size, but this won't make any different to the other exe.
[malie.zip](https://github.com/Akaruzi/dies_aitrans/files/15236486/malie.zip)

**Comment by Akaruzi** [comment]
That's nice! @Cosetto 
As for the font in kkk, it seems that the game only uses Japnese fonts from system. However, it's possible to merge Chinese font with Japanese font using fontforge to make game use the edited Chinese font. It's just not convenient. I tried [UniversalInjectorFramework](https://github.com/AtomCrafty/UniversalInjectorFramework) to change the font but was unsuccessful.  Could you throw me some insights if you know, thanks!

**Comment by Cosetto** [comment]
Have you tried [vntextproxy](https://github.com/arcusmaximus/VNTranslationTools/releases)?

**Comment by Akaruzi** [comment]
I tried, but it doesn't seem to work with kkk. I tested other games and the vntextproxy works well.

**Comment by Cosetto** [comment]
Okay, I think I know the problem. It seems the executable is not "pure" like the original one, the APIs are still obfuscated by something, so this all I could do.

**Comment by Cosetto** [comment]
@Monaco-a-Knox @Akaruzi  Try this new KKK's exe. You can use hook to change font now, I tested with [vntextproxy's d3d9.dll](https://github.com/arcusmaximus/VNTranslationTools/releases)
<img width="1280" height="816" alt="Image" src="https://github.com/user-attachments/assets/e45df4c8-fd9c-4eab-8b01-41487050f656" />
[malie.zip](https://github.com/user-attachments/files/26301611/malie.zip)

**Comment by Akaruzi** [comment]
> @Monaco-a-Knox @Akaruzi  Try this new KKK's exe. You can use hook to change font now, I tested with [vntextproxy's d3d9.dll](https://github.com/arcusmaximus/VNTranslationTools/releases)
> <img width="1280" height="816" alt="Image" src="https://github.com/user-attachments/assets/e45df4c8-fd9c-4eab-8b01-41487050f656" />
> [malie.zip](https://github.com/user-attachments/files/26301611/malie.zip)

Cool, that would be helpful

**Comment by Cosetto** [comment]
One more thing, I used Scylla to restore the IAT for hooking. It imports combase.dll, so window 7 or lower can't run the exe.
<img width="233" height="603" alt="Image" src="https://github.com/user-attachments/assets/164e65a5-36b9-4eef-8321-bde41d56f8fe" />

**Comment by Cosetto** [comment]
I manage to rotate the select text, but gonna analyze it little more
<img width="1280" height="816" alt="Image" src="https://github.com/user-attachments/assets/3bae0a3f-cab6-4580-b88a-d6ac332f7b60" />

**Comment by Cosetto** [comment]
@Monaco-a-Knox @Akaruzi  Choice and backlog are in vertical display now. Note: You have to patch the exe or use the hook to patch, else the choices will overlap.  There's also a code to create new DZI
<img width="1281" height="753" alt="Image" src="https://github.com/user-attachments/assets/40973649-3ee6-4eaa-8d40-6ecadd19006f" />
<img width="1279" height="751" alt="Image" src="https://github.com/user-attachments/assets/435efa56-5b58-4313-b651-b07d8104157f" />
[KKK_choice+backlog.zip](https://github.com/user-attachments/files/26346642/KKK_choice%2Bbacklog.zip)
