### ISSUE TITLE
resource hacker访问冲突

### ISSUE THREAD

**Issue by munic-sjj** [Akaruzi/dies_aitrans#5]
你好，当我想把exec.dat文件用resource hacker导入exe时，resource hacker显示访问冲突
![Resource Hacker - malie exe 28_10_2024 下午 6_46_06](https://github.com/user-attachments/assets/00311292-a38d-4a52-b14d-b1c657f32d94)
想问问你用的resource hacker的什么版本

**Comment by Akaruzi** [comment]
没必要用resource hacker了，建议直接用santa53x写的([Malie's Packer](https://github.com/Akaruzi/dies_aitrans/tree/master/Tools/Malie's%20Packer))把exec.dat打包进data文件，只需要用十六进制编辑器看游戏dat文件的前面几个地址，改下参数就可以了
